# Indah Kurnianda Ramadhani

K-Nearest Neighbor Algorithm in Predicting The Success of Cryotherapy Treatment Method in The Treatment of Wart Disease

In [480]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [481]:
cryotherapy = pd.read_csv("cryotherapy_.txt")
cryotherapy.head()

Sex  Age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0    1   35  12.00                5     1   100                    0
1    1   29   7.00                5     1    96                    1
2    1   50   8.00                1     3   132                    0
3    1   32  11.75                7     3   750                    0
4    1   67   9.25                1     1    42                    0

In [482]:
cryotherapy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
Sex                    90 non-null int64
Age                    90 non-null int64
Time                   90 non-null float64
Number_of_Warts        90 non-null int64
Type                   90 non-null int64
Area                   90 non-null int64
Result_of_Treatment    90 non-null int64
dtypes: float64(1), int64(6)
memory usage: 5.0 KB


In [483]:
# Variabel independen
x = cryotherapy.drop(["Result_of_Treatment"], axis = 1)
x.head()

Sex  Age   Time  Number_of_Warts  Type  Area
0    1   35  12.00                5     1   100
1    1   29   7.00                5     1    96
2    1   50   8.00                1     3   132
3    1   32  11.75                7     3   750
4    1   67   9.25                1     1    42

In [484]:
# Variabel dependen
y = cryotherapy["Result_of_Treatment"]
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Result_of_Treatment, dtype: int64

In [485]:
from sklearn.model_selection import train_test_split

In [486]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [487]:
y_test

60    1
70    0
29    1
53    0
86    1
4     0
31    1
76    0
75    1
69    0
33    0
51    1
8     1
62    0
82    1
35    1
28    0
74    0
Name: Result_of_Treatment, dtype: int64

In [488]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

## Klasifikasi: K-Nearest Neighbor

In [489]:
from sklearn.neighbors import KNeighborsClassifier

In [490]:
Classifier = KNeighborsClassifier(n_neighbors=8)

In [491]:
Classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [492]:
y_pred = Classifier.predict(x_test) 
y_pred

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [493]:
Classifier.predict_proba(x_test)

array([[0.25 , 0.75 ],
       [0.75 , 0.25 ],
       [0.25 , 0.75 ],
       [0.875, 0.125],
       [0.   , 1.   ],
       [0.875, 0.125],
       [0.25 , 0.75 ],
       [0.75 , 0.25 ],
       [0.   , 1.   ],
       [0.75 , 0.25 ],
       [1.   , 0.   ],
       [0.5  , 0.5  ],
       [0.   , 1.   ],
       [0.875, 0.125],
       [0.125, 0.875],
       [0.875, 0.125],
       [0.875, 0.125],
       [0.125, 0.875]])

## Confusion Matrix

In [494]:
from sklearn.metrics import classification_report, confusion_matrix

In [495]:
print(confusion_matrix(y_test, y_pred))

[[8 1]
 [2 7]]


In [496]:
y_actual = pd.Series([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0], name = "actual")
y_pred = pd.Series([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1], name = "prediction")

In [497]:
df_confusion = pd.crosstab(y_actual, y_pred)
df_confusion

prediction  0  1
actual          
0           8  1
1           2  7

In [498]:
from sklearn.metrics import classification_report

In [499]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.80      0.89      0.84         9
          1       0.88      0.78      0.82         9

avg / total       0.84      0.83      0.83        18



In [500]:
Accuracy = (8+7)/18
Accuracy

0.8333333333333334

In [501]:
from pycm import*

In [502]:
y_actual1=[1,0,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0]
y_pred1=[1,0,1,0,1,0,1,0,1,0,0,0,1,0,1,0,0,1]

In [503]:
print(ConfusionMatrix(y_actual1, y_pred1))

Predict          0    1    
Actual
0                8    1    

1                2    7    





Overall Statistics : 

95% CI                                                           (0.66116,1.0055)
AUNP                                                             0.83333
AUNU                                                             0.83333
Bennett S                                                        0.66667
CBA                                                              0.78889
Chi-Squared                                                      8.1
Chi-Squared DF                                                   1
Conditional Entropy                                              0.63373
Cramer V                                                         0.67082
Cross Entropy                                                    1.00896
Gwet AC1                                                         0.66769
Hamming Loss                                                     0.16667
Joint